### PR TITLE
Fix: allowed pools migration

### LINKED ISSUE #1101: Create a Migration plan
Add migration of the product, productTypes and allowedPools

### PR DESCRIPTION
**Pull request by MilGard91**
## Context

Currently the function for migration only supports migrating products and product types

closes #1101 

## Changes proposed in this pull request

- Add migration of the allowed pools to migration function
- Rename the function from `migrateProductsAndProductTypes` to `migrateCoverData`

## Test plan

Test will be added to the fork tests

## Checklist

- [x] Rebased the base branch
- [x] Attached corresponding Github issue
- [x] Prefixed the name with the type of change (i.e. feat, chore, test)
- [x] Performed a self-review of my own code
- [x] Followed the style guidelines of this project
- [ ] Made corresponding changes to the documentation
- [x] Didn't generate new warnings
- [x] Didn't generate failures on existing tests
- [ ] Added tests that prove my fix is effective or that my feature works

## Review

When reviewing a PR, please indicate intention in comments using the following emojis:
* :cake: = Nice to have but not essential.
* :bulb: = Suggestion or a comment based on personal opinion
* :hammer: = I believe this should be changed.
* :thinking: = I don’t understand something, do you mind giving me more context?
* :rocket: = Feedback

### CODE REVIEW

File: test/unit/CoverProducts/migrateProductsAndProductTypes.js
Comment (shark0der) [inline test/unit/CoverProducts/migrateProductsAndProductTypes.js:1]: Did you intend to remove this file?

File: test/unit/CoverProducts/migrateCoverData.js [hunk 1]
```diff
@@ -0,0 +1,106 @@
...
+      expect(products[i].coverAssets).to.be.equal(productsList[i].coverAssets);
+      expect(products[i].initialPriceRatio).to.be.equal(productsList[i].initialPriceRatio);
+      expect(products[i].capacityReductionRatio).to.be.equal(productsList[i].capacityReductionRatio);
+      expect(products[i].isDeprecated).to.be.equal(productsList[i].isDeprecated);
+      expect(products[i].useFixedPrice).to.be.equal(productsList[i].useFixedPrice);
+
+      const allowedPoolsAfter = await coverProducts.getAllowedPools(i);
+      const productName = await coverProducts.getProductName(i);
+
+      expect(allowedPoolsAfter).to.be.deep.equal(allowedPools[i]);
```
Comment (shark0der) [inline test/unit/CoverProducts/migrateCoverData.js:73]: Find a way to assert that we have:
- at least one product with 1 allowed pool
- at least one product with 2 or more allowed pools

Currently this entirely depends on the data in setup.js so it's prone to human errors

Comment (MilGard91) [reply test/unit/CoverProducts/migrateCoverData.js:73]: Fork tests pass, where we have all these cases. Again I can modify the setup but like you said it's prone to human errors

**Review by shark0der — APPROVED** [review]
