### PR TITLE
Test/ add missing tests for coverNFT

### LINKED ISSUE #464: V2 Cover unit tests: CoverNFT.sol
**CoverNFT.sol**

mint
- [ ] Should revert if caller is not operator
- [ ] Should mint the tokenId to the address

burn
- [ ] Should revert if caller is not operator
- [ ] Should burn the token id
- [ ] operatorTransferFrom
- [ ] Should revert if caller is not operator
- [ ] Should revert if incorrect owner address
- [ ] Should revert if recipient is address zero
- [ ] Should correctly transfer the tokenId

changeOperator
- [ ] Should revert if caller is not operator
- [ ] Should revert if new operator is address zero?
- [ ] Should set the new operator address

### PR DESCRIPTION
**Pull request by paterson1**
## Context

Closes #464

## Changes proposed in this pull request

Changed `CoverNFT` to avoid `address(0)` being set as a new operator and added some tests for `changeOperator`. 

## Checklist

- [x] Rebased the base branch
- [x] Attached corresponding Github issue
- [x] Prefixed the name with the type of change (i.e. feat, chore, test)
- [x] Performed a self-review of my own code
- [x] Followed the style guidelines of this project
- [ ] Made corresponding changes to the documentation
- [x] Didn't generate new warnings
- [x] Didn't generate failures on existing tests
- [x] Added tests that prove my fix is effective or that my feature works

## Review

When reviewing a PR, please indicate intention in comments using the following emojis:
* :cake: = Nice to have but not essential.
* :bulb: = Suggestion or a comment based on personal opinion
* :hammer: = I believe this should be changed.
* :thinking: = I don’t understand something, do you mind giving me more context?
* :rocket: = Feedback

### CODE REVIEW

File: test/unit/Cover/coverNFT.js [hunk 1]
```diff
@@ -9,98 +9,159 @@ describe('CoverNFT', function () {
...
-    await coverNFT.connect(members[0]).mint(members[1].address, 0);
-    await coverNFT.connect(members[1]).setApprovalForAll(members[0].address, true);
-    expect(await coverNFT.isApprovedOrOwner(members[0].address, 0)).to.be.equal(true);
-    expect(await coverNFT.isApprovedOrOwner(members[1].address, 0)).to.be.equal(true);
+    const {
+      members: [operator, nftOwner],
+    } = this.accounts;
+    await coverNFT.setMockOperator(operator.address);
+    await coverNFT.connect(operator).mint(nftOwner.address, 0);
+    await coverNFT.connect(nftOwner).setApprovalForAll(operator.address, true);
```
Comment (danoctavian) [inline test/unit/Cover/coverNFT.js:67]: let's use a different address here and not operator.

arbitrary address so there's no confusion that the operator has special permissions.

File: test/unit/Cover/coverNFT.js [hunk 2]
```diff
@@ -9,98 +9,159 @@ describe('CoverNFT', function () {
...
-    await coverNFT.connect(members[0]).mint(members[1].address, 0);
-    await coverNFT.connect(members[1]).approve(members[0].address, 0);
-    expect(await coverNFT.isApprovedOrOwner(members[0].address, 0)).to.be.equal(true);
-    expect(await coverNFT.isApprovedOrOwner(members[1].address, 0)).to.be.equal(true);
+    const {
+      members: [operator, nftOwner],
+    } = this.accounts;
+    await coverNFT.setMockOperator(operator.address);
+    await coverNFT.connect(operator).mint(nftOwner.address, 0);
+    await coverNFT.connect(nftOwner).approve(operator.address, 0);
```
Comment (danoctavian) [inline test/unit/Cover/coverNFT.js:79]: use an arbitrary address and not operator

**Review by danoctavian — CHANGES_REQUESTED** [review]
Small changes required

**Review by danoctavian — APPROVED** [review]
LGTM
