### PR TITLE
Test/ Refactor of swap operator tests

### LINKED ISSUE #390: Cleanup CowSwap unit tests
CowSwap unit tests contain multiple nested `describe`s that lead to unexpected test execution order.
Let's remove the nested describes.

### PR DESCRIPTION
**Pull request by paterson1**
## Context

Closes #390

## Changes proposed in this pull request

Refactored out some common constants between `placeOrder` and `closeOrder`. Also tried to flatten the nesting of `describe` blocks without losing too much context for each unit test.

## Checklist

- [x] Rebased the base branch
- [x] Attached corresponding Github issue
- [x] Prefixed the name with the type of change (i.e. feat, chore, test)
- [x] Performed a self-review of my own code
- [x] Followed the style guidelines of this project
- [ ] Made corresponding changes to the documentation
- [x] Didn't generate new warnings
- [x] Didn't generate failures on existing tests
- [ ] Added tests that prove my fix is effective or that my feature works

## Review

When reviewing a PR, please indicate intention in comments using the following emojis:
* :cake: = Nice to have but not essential.
* :bulb: = Suggestion or a comment based on personal opinion
* :hammer: = I believe this should be changed.
* :thinking: = I don’t understand something, do you mind giving me more context?
* :rocket: = Feedback

### CODE REVIEW

File: test/unit/SwapOperator/closeOrder.js [hunk 1]
```diff
@@ -127,36 +94,34 @@ describe('closeOrder', function () {
     await swapOperator.placeOrder(contractOrder, orderUID);
   });
 
-  describe('access control', function () {
-    it('before deadline, its callable only by controller', async function () {
-      const deadline = order.validTo;
-      const snapshot = await takeSnapshot();
+  it('before deadline, its callable only by controller', async function () {
+    const deadline = order.validTo;
+    const snapshot = await takeSnapshot();
```
Comment (danoctavian) [inline test/unit/SwapOperator/closeOrder.js:99]: normally we have a beforeEach and afterEach to handle the snapshot encirclement

We should do the same here 

https://github.com/NexusMutual/smart-contracts/blob/862539ae93e7c00d5ccb9069f5afa0c5fcd4704e/test/unit/Assessment/index.js#L8

File: test/unit/SwapOperator/closeOrder.js [hunk 2]
```diff
@@ -127,36 +94,34 @@ describe('closeOrder', function () {
...
-      const deadline = order.validTo;
-      const snapshot = await takeSnapshot();
+  it('after deadline, its callable by anyone', async function () {
+    const deadline = order.validTo;
+    const snapshot = await takeSnapshot();
 
-      // Executing as non-controller should succeed
-      await setNextBlockTime(deadline + 1);
-      await swapOperator.connect(governance).closeOrder(contractOrder);
+    // Executing as non-controller should succeed
```
Comment (danoctavian) [inline test/unit/SwapOperator/closeOrder.js:117]: let's make this address some random address not governance so the test is accurate

File: test/unit/SwapOperator/closeOrder.js [hunk 3]
```diff
@@ -258,126 +221,120 @@ describe('closeOrder', function () {
...
-        orderUID,
-        order.sellAmount.div(2),
-        order.feeAmount.div(2),
-        order.buyAmount.div(2),
-      );
-      await expect(swapOperator.closeOrder(contractOrder))
-        .to.emit(swapOperator, 'OrderClosed')
-        .withArgs(makeOrderTuple(contractOrder), order.sellAmount.div(2));
-    });
+  it('emitting OrderClosed event when order was partially filled', async function () {
```
Comment (danoctavian) [inline test/unit/SwapOperator/closeOrder.js:319]: emits OrderClosed event

File: test/unit/SwapOperator/closeOrder.js [hunk 4]
```diff
@@ -258,126 +221,120 @@ describe('closeOrder', function () {
...
+      order.buyAmount.div(2),
+    );
+    await expect(swapOperator.closeOrder(contractOrder))
+      .to.emit(swapOperator, 'OrderClosed')
+      .withArgs(makeOrderTuple(contractOrder), order.sellAmount.div(2));
+  });
 
-    it('when order was fully filled', async function () {
-      await cowSettlement.fill(contractOrder, orderUID, order.sellAmount, order.feeAmount, order.buyAmount);
+  it('emitting OrderClosed event when order was fully filled', async function () {
```
Comment (danoctavian) [inline test/unit/SwapOperator/closeOrder.js:332]: emits OrderClosed event

File: test/unit/SwapOperator/closeOrder.js [hunk 5]
```diff
@@ -258,126 +221,120 @@ describe('closeOrder', function () {
...
-      expect(await weth.balanceOf(swapOperator.address)).to.eq(0);
-    });
+    expect(await ethers.provider.getBalance(pool.address)).to.eq(initialPoolEth.add(initialOperatorWeth));
+    expect(await weth.balanceOf(swapOperator.address)).to.eq(0);
+  });
 
-    it('transfers the erc20 token to pool if its not weth', async function () {
-      // Cancel current order
-      await swapOperator.closeOrder(contractOrder);
+  it('returning sellToken to pool transfers the erc20 token to pool if its not weth', async function () {
```
Comment (danoctavian) [inline test/unit/SwapOperator/closeOrder.js:285]: 'transfers erc20 sellToken to pool if its not weth'

File: test/unit/SwapOperator/closeOrder.js [hunk 6]
```diff
@@ -183,71 +148,69 @@ describe('closeOrder', function () {
     await expect(swapOperator.closeOrder(contractOrder)).to.be.revertedWith('SwapOp: No order in place');
   });
 
-  describe('canceling the presignature and allowance', function () {
-    it('does so if the order was not filled at all', async function () {
-      expect(await cowSettlement.presignatures(orderUID)).to.equal(true);
-      expect(await weth.allowance(swapOperator.address, cowVaultRelayer.address)).to.eq(
-        order.sellAmount.add(order.feeAmount),
-      );
+  it('canceling the presignature and allowance: does so if the order was not filled at all', async function () {
```
Comment (danoctavian) [inline test/unit/SwapOperator/closeOrder.js:151]: 'presignature is false and allowance is 0 when order was not filled at all'

File: test/unit/SwapOperator/closeOrder.js [hunk 7]
```diff
@@ -183,71 +148,69 @@ describe('closeOrder', function () {
...
-
-      // Fill 50% of order
-      await cowSettlement.fill(
-        contractOrder,
-        orderUID,
-        order.sellAmount.div(2),
-        order.feeAmount.div(2),
-        order.buyAmount.div(2),
-      );
+  it('canceling the presignature and allowance: does so if the order is partially filled', async function () {
```
Comment (danoctavian) [inline test/unit/SwapOperator/closeOrder.js:163]: cancels presignature and allowance when the order is partially filled

File: test/unit/SwapOperator/closeOrder.js [hunk 8]
```diff
@@ -183,71 +148,69 @@ describe('closeOrder', function () {
...
+  });
 
-    it('does so if the order was fully filled', async function () {
-      expect(await cowSettlement.presignatures(orderUID)).to.equal(true);
-      expect(await weth.allowance(swapOperator.address, cowVaultRelayer.address)).to.eq(
-        order.sellAmount.add(order.feeAmount),
-      );
-      expect(await dai.balanceOf(swapOperator.address)).to.eq(0);
-      expect(await weth.balanceOf(swapOperator.address)).to.gt(0);
+  it('canceling the presignature and allowance: does so if the order was fully filled', async function () {
```
Comment (danoctavian) [inline test/unit/SwapOperator/closeOrder.js:194]: 'cancels presignature and allowance when the order is fully filled'

File: test/unit/SwapOperator/closeOrder.js [hunk 9]
```diff
@@ -258,126 +221,120 @@ describe('closeOrder', function () {
     expect(await swapOperator.currentOrderUID()).to.eq('0x');
   });
 
-  describe('withdrawing buyToken to pool', function () {
-    it('withdraws and unwraps ether if buyToken is weth', async function () {
-      // Cancel current order
-      await swapOperator.closeOrder(contractOrder);
+  it('withdrawing buyToken to pool withdraws and unwraps ether if buyToken is weth', async function () {
```
Comment (danoctavian) [inline test/unit/SwapOperator/closeOrder.js:224]: withdraws buyToken to pool and unwraps ether if buyToken is weth

File: test/unit/SwapOperator/closeOrder.js [hunk 10]
```diff
@@ -258,126 +221,120 @@ describe('closeOrder', function () {
...
-      expect(await ethers.provider.getBalance(pool.address)).to.eq(initialPoolEth.add(order.buyAmount));
-    });
+    expect(await weth.balanceOf(swapOperator.address)).to.eq(0);
+    expect(await ethers.provider.getBalance(pool.address)).to.eq(initialPoolEth.add(order.buyAmount));
+  });
 
-    it('transfer the erc20 token if its not weth', async function () {
-      expect(await dai.balanceOf(swapOperator.address)).to.eq(0);
-      expect(await dai.balanceOf(pool.address)).to.eq(0);
+  it('withdrawing buyToken to pool transfer the erc20 token if its not weth', async function () {
```
Comment (danoctavian) [inline test/unit/SwapOperator/closeOrder.js:253]: withdraws buyToken to pool when buyToken is an erc20 token

File: test/unit/SwapOperator/closeOrder.js [hunk 11]
```diff
@@ -258,126 +221,120 @@ describe('closeOrder', function () {
...
-    });
+    expect(await dai.balanceOf(swapOperator.address)).to.eq(0);
+    expect(await dai.balanceOf(pool.address)).to.eq(order.buyAmount.add(extraAmount));
   });
 
-  describe('returning sellToken to pool', function () {
-    it('withdraws and unwraps ether if sellToken is weth', async function () {
-      const initialPoolEth = await ethers.provider.getBalance(pool.address);
-      const initialOperatorWeth = await weth.balanceOf(swapOperator.address);
+  it('returning sellToken to pool withdraws and unwraps ether if sellToken is weth', async function () {
```
Comment (danoctavian) [inline test/unit/SwapOperator/closeOrder.js:272]: returns sellToken to pool and unwraps ether if sellToken is weth

File: test/unit/SwapOperator/closeOrder.js (hunk 5 above)
Comment (danoctavian) [inline test/unit/SwapOperator/closeOrder.js:285]: returns sellToken to pool when sellToken is an erc20 token

File: test/unit/SwapOperator/closeOrder.js [hunk 12]
```diff
@@ -258,126 +221,120 @@ describe('closeOrder', function () {
...
+    expect(await dai.balanceOf(swapOperator.address)).to.eq(0);
   });
 
-  describe('emitting OrderClosed event', function () {
-    it('when order was not filled', async function () {
-      await expect(swapOperator.closeOrder(contractOrder))
-        .to.emit(swapOperator, 'OrderClosed')
-        .withArgs(makeOrderTuple(contractOrder), 0);
-    });
+  it('when order was not filled', async function () {
```
Comment (danoctavian) [inline test/unit/SwapOperator/closeOrder.js:313]: emits OrderClosed event when order was not filled

File: test/unit/SwapOperator/placeOrder.js [hunk 13]
```diff
@@ -296,353 +279,334 @@ describe('placeOrder', function () {
...
-      await swapOperator.placeOrder(newContractOrder, newOrderUID);
-    });
+    // Order buying WETH (eth) still should succeed
+    await swapOperator.placeOrder(newContractOrder, newOrderUID);
+  });
 
-    it('performs the validation when buyToken is not WETH', async function () {
-      // Since DAI was already registered on setup, set its details to 0
-      await pool.connect(governance).setSwapDetails(dai.address, 0, 0, 0, true); // otherSigner is governant
+  it('performs the validation assets details when buyToken is not WETH', async function () {
```
Comment (danoctavian) [inline test/unit/SwapOperator/placeOrder.js:294]: validates asset details when buyToken is not WETH

File: test/unit/SwapOperator/placeOrder.js [hunk 14]
```diff
@@ -296,353 +279,334 @@ describe('placeOrder', function () {
...
 
-      await swapOperator.placeOrder(newContractOrder, newOrderUID);
+    expect(poolDaiBefore.sub(poolDaiAfter)).to.eq(newOrder.sellAmount.add(newOrder.feeAmount));
+    expect(swapOpDaiAfter.sub(swapOpDaiBefore)).to.eq(newOrder.sellAmount.add(newOrder.feeAmount));
+  });
 
-      lastSwapTime = (await pool.getAssetSwapDetails(dai.address)).lastSwapTime;
-      expect(lastSwapTime).to.eq(await lastBlockTimestamp());
-    });
+  it('setting lastSwapDate: sets it on buyAsset when selling ETH', async function () {
```
Comment (danoctavian) [inline test/unit/SwapOperator/placeOrder.js:573]: sets lastSwapDate on buyAsset when selling ETH

File: test/unit/SwapOperator/placeOrder.js [hunk 15]
```diff
@@ -296,353 +279,334 @@ describe('placeOrder', function () {
...
+    await swapOperator.placeOrder(contractOrder, orderUID);
+
+    lastSwapTime = (await pool.getAssetSwapDetails(dai.address)).lastSwapTime;
+    expect(lastSwapTime).to.eq(await lastBlockTimestamp());
   });
 
-  describe('setting pools swapValue', function () {
-    it('works when selling eth', async function () {
-      expect(await pool.swapValue()).to.eq(0);
+  it('setting lastSwapDate: sets it on sellAsset when buying ETH', async function () {
```
Comment (danoctavian) [inline test/unit/SwapOperator/placeOrder.js:583]: sets lastSwapDate on sellAsset when selling ETH

**Review by danoctavian — CHANGES_REQUESTED** [review]
Test description renames required

**Review by danoctavian — APPROVED** [review]
LGTM
